import { Activity, BarChart3, MapPinned, Timer, TrendingUp } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { MetricCard } from '../components/MetricCard'
import { PageHeader } from '../components/PageHeader'
import { departmentData, trendData } from '../data/mock'
import { Panel, PanelHead } from '../components/ui/Panel'

export function AnalyticsPage(){
  return <div className="mx-auto w-full max-w-[1540px]"><PageHeader eyebrow="Executive intelligence" title="Municipal analytics" description="High-level service patterns, geographic pressure and operational performance."/>
    <div className="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard icon={Activity} label="Resolution rate" value="86.4%" note="+4.2 pp vs last month" tone="mint"/><MetricCard icon={Timer} label="Median resolution" value="2.8d" note="0.6d faster"/><MetricCard icon={MapPinned} label="Hotspot wards" value="3" note="Ward 04 leads demand"/><MetricCard icon={TrendingUp} label="Demand change" value="+12.3%" note="Month-over-month" tone="dark"/></div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Panel><PanelHead eyebrow="Weekly throughput" title="Opened and resolved requests"/><div className="h-[380px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={trendData}><CartesianGrid vertical={false} stroke="#e8edf3"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="opened" fill="#cbd5e1" radius={[5,5,0,0]}/><Bar dataKey="resolved" fill="#0f766e" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel>
      <Panel><PanelHead eyebrow="Department score" title="Service health"/><div className="grid gap-3">{departmentData.map((d,i)=><div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4" key={d.name}><span className="text-[9px] font-extrabold text-slate-400">0{i+1}</span><div className="min-w-0 flex-1"><strong className="block text-[11px]">{d.name}</strong><small className="mt-1 block text-[9px] text-slate-500">{d.open} open cases</small></div><em className="not-italic text-[12px] font-extrabold text-teal-700">{d.score}%</em></div>)}</div></Panel>
      <Panel className="relative overflow-hidden bg-slate-950 text-white"><span className="text-[9px] font-extrabold uppercase tracking-[.15em] text-teal-300">Geographic pressure</span><h2 className="mt-2 max-w-xl font-['Manrope'] text-3xl font-extrabold tracking-[-.04em]">Ward 04 is the clearest concentration.</h2><p className="mt-3 max-w-xl text-[12px] leading-6 text-slate-300">Environmental and road-service reports account for most of the current demand cluster.</p><div className="relative mt-8 h-44 overflow-hidden rounded-2xl bg-gradient-to-br from-slate-900 to-teal-950"><span className="absolute left-[22%] top-[24%] h-16 w-16 rounded-full bg-orange-500/35 blur-xl"/><span className="absolute right-[18%] top-[38%] h-24 w-24 rounded-full bg-teal-400/25 blur-2xl"/><span className="absolute bottom-[15%] left-[45%] h-14 w-14 rounded-full bg-rose-500/30 blur-xl"/><i className="absolute left-6 right-6 top-1/2 h-px -rotate-6 bg-white/15"/><b className="absolute bottom-5 left-5 text-[10px] tracking-[.16em] text-white/70">WARD 04</b></div></Panel>
      <Panel><PanelHead eyebrow="Request mix" title="By service type" right={<BarChart3 size={20} className="text-slate-400"/>}/><div className="grid gap-4">{[['Complaints','62%'],['Inquiries','17%'],['Suggestions','12%'],['Bookings','9%']].map(([n,v])=><div key={n} className="grid grid-cols-[90px_1fr_42px] items-center gap-3 text-[10px]"><span>{n}</span><div className="h-2 overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full bg-teal-700" style={{width:v}}/></div><strong className="text-right">{v}</strong></div>)}</div></Panel>
    </div>
  </div>
}
