import { Building2, Clock3, Mail, MapPin, Phone, Send } from 'lucide-react'
import { CivicMap } from '../components/CivicMap'
import { PublicFooter } from '../components/PublicFooter'
import { PublicHeader } from '../components/PublicHeader'
import { PublicInnerHero } from '../components/PublicInnerHero'
import { ScrollReveal } from '../components/ScrollReveal'
import { Input, Textarea } from '../components/ui/Field'

export function ContactPage() {
  return <div className="min-h-screen bg-white pt-[88px] font-['DM_Sans'] text-slate-950 max-[860px]:pt-[70px]"><PublicHeader/><main>
    <PublicInnerHero image="/lgs-media/map-south.jpg" kicker="Contact" title={<>Get in touch<br/>with your municipality.</>} body="Use LGS online when possible, or reach the municipal team directly for support, partnerships and service information."/>
    <section className="py-24 sm:py-28"><div className="mx-auto grid w-[min(1500px,calc(100%-80px))] gap-14 max-[1100px]:w-[calc(100%-48px)] max-[780px]:w-[calc(100%-32px)] lg:grid-cols-[.8fr_1.2fr] lg:gap-20">
      <ScrollReveal direction="left"><div><span className="text-[10px] font-extrabold uppercase tracking-[.17em] text-teal-700">Municipal office</span><h2 className="mt-5 font-['Manrope'] text-[clamp(42px,5vw,72px)] font-extrabold leading-[.95] tracking-[-.045em]">Talk to the LGS team.</h2><p className="mt-5 text-sm leading-7 text-slate-500">For platform support, civic partnerships or municipal implementation questions, send us a message.</p><div className="mt-8 grid gap-5">{[[MapPin,'Address','Weddemulla Demo Council, Sri Lanka'],[Phone,'Phone','+94 11 000 0000'],[Mail,'Email','hello@lgs.example'],[Clock3,'Office hours','Mon–Fri · 8:30 AM–4:15 PM']].map(([Icon,label,value])=>{const C=Icon as typeof MapPin;return <div className="flex items-start gap-4" key={String(label)}><C size={20} className="mt-0.5 text-teal-700"/><span><small className="block text-[9px] font-extrabold uppercase tracking-[.13em] text-slate-400">{String(label)}</small><strong className="mt-1 block text-[12px]">{String(value)}</strong></span></div>})}</div></div></ScrollReveal>
      <ScrollReveal direction="right"><form className="grid gap-4 rounded-3xl border border-slate-200 bg-slate-50 p-6 sm:p-8"><Input placeholder="Your name"/><div className="grid gap-4 sm:grid-cols-2"><Input type="email" placeholder="you@example.com"/><Input placeholder="How can we help?"/></div><Textarea rows={7} placeholder="Tell us what you would like to discuss…"/><button type="button" className="inline-flex min-h-[52px] w-fit items-center gap-2 rounded-md bg-slate-950 px-6 text-[11px] font-extrabold uppercase tracking-[.06em] text-white hover:bg-slate-800"><Send size={16}/>Send message</button></form></ScrollReveal>
    </div></section>
    <section className="pb-24"><div className="mx-auto grid w-[min(1500px,calc(100%-80px))] gap-5 max-[1100px]:w-[calc(100%-48px)] max-[780px]:w-[calc(100%-32px)] lg:grid-cols-3">{[[Building2,'Municipal headquarters','Weddemulla Demo Council','Primary administration and public service desk'],[MapPin,'Field services','Municipal operations','Inspections, site work and service coordination'],[ShieldIcon,'Digital services','LGS support','Map, account and online request assistance']].map(([Icon,title,sub,body],i)=>{const C=Icon as typeof Building2;return <ScrollReveal key={String(title)} delay={i*100}><article className="min-h-[290px] rounded-2xl border border-slate-200 p-8 text-center transition hover:-translate-y-1 hover:border-teal-200 hover:bg-teal-50/40 hover:shadow-xl"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-slate-100 text-teal-700"><C/></span><h3 className="mt-6 font-['Manrope'] text-xl font-extrabold uppercase">{String(title)}</h3><strong className="mt-2 block text-[12px]">{String(sub)}</strong><p className="mt-3 text-[11px] leading-6 text-slate-500">{String(body)}</p></article></ScrollReveal>})}</div></section>
    <section className="relative h-[620px] overflow-hidden"><CivicMap mode="preview"/><div className="absolute bottom-8 left-1/2 z-[1000] flex -translate-x-1/2 items-center gap-4 bg-white px-6 py-3 shadow-xl"><span className="text-[9px] font-extrabold uppercase tracking-[.13em] text-slate-400">Municipal map</span><strong className="text-[12px]">Weddemulla Estate</strong></div></section>
  </main><PublicFooter/></div>
}

function ShieldIcon(){return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></svg>}
