import { ArrowLeft, Camera, Check, CheckCircle2, ClipboardCheck, Clock3, FileText, MapPin, MessageSquarePlus, Navigation, UserRound, XCircle } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { StatusBadge, TypeBadge } from '../components/StatusBadge'
import { useAuth } from '../context/AuthContext'
import { buildings, requests } from '../data/mock'
import { Panel, PanelHead } from '../components/ui/Panel'
import { Button } from '../components/ui/Button'

export function RequestDetailPage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { user } = useAuth()
  const request = requests.find(r=>r.id===id)
  if(!request||!user) return <div className="mx-auto max-w-5xl"><div className="rounded-3xl border border-slate-200 bg-white p-10 text-center"><h2 className="font-['Manrope'] text-2xl font-extrabold">Request not found</h2><Button variant="secondary" className="mt-5" onClick={()=>navigate('/app/requests')}>Back to requests</Button></div></div>
  if(user.role==='CITIZEN'&&request.createdBy!==user.id) return <div className="mx-auto max-w-5xl"><div className="rounded-3xl border border-slate-200 bg-white p-10 text-center"><h2 className="font-['Manrope'] text-2xl font-extrabold">This request is private.</h2><p className="mt-2 text-sm text-slate-500">Citizens can only view their own request details.</p><Link className="mt-5 inline-flex min-h-11 items-center rounded-xl border border-slate-200 px-4 text-[12px] font-extrabold" to="/app/requests">My requests</Link></div></div>
  const building=buildings.find(b=>b.id===request.buildingId)
  const canOperate=user.role==='GOV_WORKER'||user.role==='GOV_ADMIN'
  const canApprove=user.role==='APPROVER'||user.role==='SUPERIOR'
  return <div className="mx-auto w-full max-w-[1500px]"><button className="mb-5 inline-flex items-center gap-2 text-[11px] font-bold text-slate-500 hover:text-slate-900" onClick={()=>navigate(-1)}><ArrowLeft size={15}/>Back</button>
    <div className="mb-6 flex flex-col justify-between gap-5 rounded-3xl border border-slate-200 bg-white p-6 sm:p-7 lg:flex-row"><div className="max-w-4xl"><div className="flex flex-wrap gap-2"><TypeBadge type={request.type}/><StatusBadge status={request.status}/></div><span className="mt-5 block text-[10px] font-extrabold text-slate-400">{request.id}</span><h1 className="mt-2 font-['Manrope'] text-3xl font-extrabold tracking-[-.04em] sm:text-4xl">{request.title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-500">{request.description}</p></div><div className="min-w-[190px] rounded-2xl bg-slate-950 p-5 text-white"><small className="text-[9px] font-extrabold uppercase tracking-[.12em] text-slate-400">Priority</small><strong className="mt-2 block font-['Manrope'] text-2xl font-extrabold">{request.priority}</strong><span className="mt-4 block text-[10px] leading-5 text-slate-400">Last updated<br/>{new Date(request.updatedAt).toLocaleDateString()}</span></div></div>
    <div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><main className="grid gap-5"><Panel><PanelHead eyebrow="Status history" title="Request timeline"/><div className="grid gap-0">{request.history.map((event,index)=><div className="relative grid grid-cols-[36px_1fr] gap-3 pb-6 last:pb-0" key={`${event.status}-${index}`}><span className="relative z-10 grid h-8 w-8 place-items-center rounded-full bg-teal-700 text-white"><Check size={13}/></span>{index<request.history.length-1&&<i className="absolute bottom-0 left-[15px] top-8 w-px bg-slate-200"/>}<div><StatusBadge status={event.status}/><strong className="mt-2 block text-[12px]">{event.label}</strong>{event.note&&<p className="mt-1 text-[11px] leading-5 text-slate-500">{event.note}</p>}<small className="mt-1 block text-[9px] text-slate-400">{event.at} · {event.by}</small></div></div>)}</div></Panel>
      <Panel><PanelHead eyebrow="Evidence" title="Photos & documents"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{request.photos.length?request.photos.map((p,i)=><div className="flex min-h-28 items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4" key={p}><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-teal-700"><Camera size={22}/></span><span><strong className="block text-[11px]">{p}</strong><small className="mt-1 block text-[9px] text-slate-400">Evidence image {i+1}</small></span></div>):<div className="flex min-h-28 items-center gap-3 rounded-2xl border border-dashed border-slate-300 p-4 text-slate-500"><FileText size={22}/><span className="text-[11px]">No evidence files attached</span></div>}</div></Panel></main>
      <aside className="grid content-start gap-5"><Panel><span className="text-[9px] font-extrabold uppercase tracking-[.15em] text-teal-700">Location</span><h3 className="mt-2 font-['Manrope'] text-xl font-extrabold">{request.locationLabel}</h3><p className="mt-2 flex items-center gap-2 text-[11px] text-slate-500"><MapPin size={15}/>{request.ward}</p>{building&&<div className="my-5 rounded-2xl bg-slate-50 p-4"><strong className="block text-[12px]">{building.name}</strong><small className="mt-1 block text-[10px] text-slate-500">{building.address}</small><span className="mt-2 block text-[9px] font-extrabold text-slate-400">{building.id}</span></div>}<Link className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-slate-200 text-[11px] font-extrabold hover:bg-slate-50" to="/app/map"><Navigation size={15}/>Open on map</Link></Panel>
      <Panel><span className="text-[9px] font-extrabold uppercase tracking-[.15em] text-teal-700">Ownership</span><div className="mt-4 grid gap-4">{[[UserRound,'Department',request.department],[ClipboardCheck,'Assigned officer',request.assignedTo?'Officer D. Fernando':'Not assigned'],[Clock3,'Created',new Date(request.createdAt).toLocaleDateString()]].map(([Icon,label,value])=>{const C=Icon as typeof UserRound;return <div className="flex items-start gap-3" key={String(label)}><C size={17} className="mt-0.5 text-slate-500"/><span><small className="block text-[9px] uppercase tracking-[.1em] text-slate-400">{String(label)}</small><strong className="mt-1 block text-[11px]">{String(value)}</strong></span></div>})}</div></Panel>
      {canOperate&&<Panel><span className="text-[9px] font-extrabold uppercase tracking-[.15em] text-teal-700">Workflow actions</span><h3 className="mt-2 font-['Manrope'] text-lg font-extrabold">Move this case forward</h3><div className="mt-5 grid gap-2">{user.role==='GOV_WORKER'&&<><Button className="w-full"><CheckCircle2 size={16}/>Start / continue inspection</Button><Button variant="secondary" className="w-full"><Camera size={16}/>Upload evidence</Button><Button variant="secondary" className="w-full"><MessageSquarePlus size={16}/>Add inspection note</Button></>}{user.role==='GOV_ADMIN'&&<><Button className="w-full"><UserRound size={16}/>Assign / reassign officer</Button><Button variant="secondary" className="w-full"><ClipboardCheck size={16}/>Escalate for approval</Button></>}</div></Panel>}
      {canApprove&&(request.status.includes('APPROVAL')||request.status==='NEEDS_APPROVAL')&&<Panel><span className="text-[9px] font-extrabold uppercase tracking-[.15em] text-teal-700">Approval decision</span><h3 className="mt-2 font-['Manrope'] text-lg font-extrabold">Review the requested action</h3><div className="mt-5 grid gap-2"><Button className="w-full"><CheckCircle2 size={16}/>Approve request</Button><Button variant="secondary" className="w-full"><MessageSquarePlus size={16}/>Request information</Button><Button variant="danger" className="w-full"><XCircle size={16}/>Reject request</Button></div></Panel>}
      </aside></div>
  </div>
}
